
package com.girosyfinanzas.servicios.direccioncanales.srvintproductscustomer;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "productsFault", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntProductsCustomer/")
public class ProductsFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private ProductsFaultType faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public ProductsFault(String message, ProductsFaultType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public ProductsFault(String message, ProductsFaultType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.girosyfinanzas.servicios.direccioncanales.srvintproductscustomer.ProductsFaultType
	 */
	public ProductsFaultType getFaultInfo() {
		return faultInfo;
	}

}
