
package com.girosyfinanzas.servicios.direccioncanales.srvintproductscustomer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntProductsCustomer service = new SrvIntProductsCustomer();
* SrvIntProductsCustomerInterface portType = service.getSrvIntProductsCustomerSOAP();
* portType.products(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntProductsCustomer", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntProductsCustomer/", wsdlLocation = "http://172.16.16.53:7860/servicios/DireccionCanales/SrvIntProductsCustomer/?wsdl")
public class SrvIntProductsCustomer extends Service {

	private final static URL SRVINTPRODUCTSCUSTOMER_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.girosyfinanzas.servicios.direccioncanales.srvintproductscustomer.SrvIntProductsCustomer.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.girosyfinanzas.servicios.direccioncanales.srvintproductscustomer.SrvIntProductsCustomer.class
					.getResource(".");
			url = new URL(baseUrl, "http://172.16.16.53:7860/servicios/DireccionCanales/SrvIntProductsCustomer/?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.16.53:7860/servicios/DireccionCanales/SrvIntProductsCustomer/?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTPRODUCTSCUSTOMER_WSDL_LOCATION = url;
	}

	public SrvIntProductsCustomer(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntProductsCustomer() {
		super(SRVINTPRODUCTSCUSTOMER_WSDL_LOCATION,
				new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntProductsCustomer/",
						"SrvIntProductsCustomer"));
	}

	/**
	 * 
	 * @return returns SrvIntProductsCustomerInterface
	 */
	@WebEndpoint(name = "SrvIntProductsCustomerSOAP")
	public SrvIntProductsCustomerInterface getSrvIntProductsCustomerSOAP() {
		return super.getPort(
				new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntProductsCustomer/",
						"SrvIntProductsCustomerSOAP"),
				SrvIntProductsCustomerInterface.class);
	}

}
