
package com.backoffice.client.bank;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "inquiryBankAccountFault", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/")
public class InquiryBankAccountFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private InquiryBankAccountFaultType faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public InquiryBankAccountFault(String message, InquiryBankAccountFaultType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public InquiryBankAccountFault(String message, InquiryBankAccountFaultType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.backoffice.client.bank.InquiryBankAccountFaultType
	 */
	public InquiryBankAccountFaultType getFaultInfo() {
		return faultInfo;
	}

}
