
package com.backoffice.client.bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SrvIntBankAccountInterface", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SrvIntBankAccountInterface {

	/**
	 * 
	 * @param inquiryBankAccountReq
	 * @return returns com.backoffice.client.bank.InquiryBankAccountRespType
	 * @throws InquiryBankAccountFault
	 */
	@WebMethod(operationName = "InquiryBankAccount", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/InquiryBankAccount")
	@WebResult(name = "inquiryBankAccountResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "inquiryBankAccountResp")
	public InquiryBankAccountRespType inquiryBankAccount(
			@WebParam(name = "inquiryBankAccountRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "inquiryBankAccountReq") InquiryBankAccountReqType inquiryBankAccountReq)
			throws InquiryBankAccountFault;

	/**
	 * 
	 * @param manageAccountsReq
	 * @return returns com.backoffice.client.bank.ManageAccountsRespType
	 * @throws ManageAccountsFault
	 */
	@WebMethod(operationName = "ManageAccounts", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/ManageAccounts")
	@WebResult(name = "manageAccountsResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "manageAccountsResp")
	public ManageAccountsRespType manageAccounts(
			@WebParam(name = "manageAccountsRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "manageAccountsReq") ManageAccountsReqType manageAccountsReq)
			throws ManageAccountsFault;

	/**
	 * 
	 * @param bankAccountServiceReq
	 * @return returns com.backoffice.client.bank.BankAccountServiceRespType
	 * @throws BankAccountServiceFault
	 */
	@WebMethod(operationName = "BankAccountService", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/BankAccountService")
	@WebResult(name = "bankAccountServiceResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "bankAccountServiceResp")
	public BankAccountServiceRespType bankAccountService(
			@WebParam(name = "bankAccountServiceRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "bankAccountServiceReq") BankAccountServiceReqType bankAccountServiceReq)
			throws BankAccountServiceFault;

	/**
	 * 
	 * @param transferSavingsAccountReq
	 * @return returns com.backoffice.client.bank.TransferSavingsAccountRespType
	 * @throws TransferSavingsAccountFault
	 */
	@WebMethod(operationName = "TransferSavingsAccount", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/TransferSavingsAccount")
	@WebResult(name = "transferSavingsAccountResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "transferSavingsAccountResponse")
	public TransferSavingsAccountRespType transferSavingsAccount(
			@WebParam(name = "transferSavingsAccountRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", partName = "transferSavingsAccountReq") TransferSavingsAccountReqType transferSavingsAccountReq)
			throws TransferSavingsAccountFault;

}
