
package com.backoffice.client.bank;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntBankAccount service = new SrvIntBankAccount();
* SrvIntBankAccountInterface portType = service.getSrvIntBankAccountPort();
* portType.inquiryBankAccount(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntBankAccount", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", wsdlLocation = "http://172.16.16.53:7805/servicios/DireccionCanales/SrvIntBankAccount/?wsdl")
@HandlerChain( file="SrvIntBankAccount.xml" )
public class SrvIntBankAccount extends Service {

	private final static URL SRVINTBANKACCOUNT_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.backoffice.client.bank.SrvIntBankAccount.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.backoffice.client.bank.SrvIntBankAccount.class.getResource(".");
			url = new URL(baseUrl, "http://172.16.16.53:7805/servicios/DireccionCanales/SrvIntBankAccount/?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.16.53:7805/servicios/DireccionCanales/SrvIntBankAccount/?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTBANKACCOUNT_WSDL_LOCATION = url;
	}

	public SrvIntBankAccount(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntBankAccount() {
		super(SRVINTBANKACCOUNT_WSDL_LOCATION, new QName(
				"http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/", "SrvIntBankAccount"));
	}

	/**
	 * 
	 * @return returns SrvIntBankAccountInterface
	 */
	@WebEndpoint(name = "SrvIntBankAccountPort")
	public SrvIntBankAccountInterface getSrvIntBankAccountPort() {
		return super.getPort(new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/",
				"SrvIntBankAccountPort"), SrvIntBankAccountInterface.class);
	}

}
