
package com.backoffice.client.bank;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "transferSavingsAccountFault", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntBankAccount/")
public class TransferSavingsAccountFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private TransferSavingsAccountFaultType faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public TransferSavingsAccountFault(String message, TransferSavingsAccountFaultType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public TransferSavingsAccountFault(String message, TransferSavingsAccountFaultType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.backoffice.client.bank.TransferSavingsAccountFaultType
	 */
	public TransferSavingsAccountFaultType getFaultInfo() {
		return faultInfo;
	}

}
