
package com.backoffice.client.customer;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "registerCustCompanyFault", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/")
public class RegisterCustomerCompanyFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private RegisterCustCompanyFaultType faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public RegisterCustomerCompanyFault(String message, RegisterCustCompanyFaultType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public RegisterCustomerCompanyFault(String message, RegisterCustCompanyFaultType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.backoffice.client.customer.RegisterCustCompanyFaultType
	 */
	public RegisterCustCompanyFaultType getFaultInfo() {
		return faultInfo;
	}

}
