
package com.backoffice.client.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SrvIntCustomerInteface", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SrvIntCustomerInteface {

	/**
	 * 
	 * @param registerReq
	 * @return returns com.backoffice.client.customer.RegisterRespType
	 * @throws RegisterFault
	 */
	@WebMethod(operationName = "Register", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/Register")
	@WebResult(name = "RegisterResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "registerResp")
	public RegisterRespType register(
			@WebParam(name = "RegisterRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "registerReq") RegisterReqType registerReq)
			throws RegisterFault;

	/**
	 * 
	 * @param registerCustCompanyReq
	 * @return returns
	 *         com.backoffice.client.customer.RegisterCustCompanyRespType
	 * @throws RegisterCustomerCompanyFault
	 */
	@WebMethod(operationName = "RegisterCustomerCompany", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/RegisterCustomerCompany")
	@WebResult(name = "registerCustCompanyResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "registerCustCompanyResp")
	public RegisterCustCompanyRespType registerCustomerCompany(
			@WebParam(name = "registerCustCompanyRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "registerCustCompanyReq") RegisterCustCompanyReqType registerCustCompanyReq)
			throws RegisterCustomerCompanyFault;

	/**
	 * 
	 * @param inquiryByIdCustCompanyReq
	 * @return returns
	 *         com.backoffice.client.customer.InquiryByIdCustCompanyRespType
	 * @throws InquiryByIdCustomerCompanyFault
	 */
	@WebMethod(operationName = "InquiryByIdCustomerCompany", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/InquiryByIdCustomerCompany")
	@WebResult(name = "inquiryByIdCustomerCompanyResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "inquiryByIdCustCompanyResp")
	public InquiryByIdCustCompanyRespType inquiryByIdCustomerCompany(
			@WebParam(name = "inquiryByIdCustomerCompanyRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "inquiryByIdCustCompanyReq") InquiryByIdCustCompanyReqType inquiryByIdCustCompanyReq)
			throws InquiryByIdCustomerCompanyFault;

	/**
	 * 
	 * @param inquiryByIdCustomerReq
	 * @return returns
	 *         com.backoffice.client.customer.InquiryByIdCustomerRespType
	 * @throws InquiryByIdCustomerFault
	 */
	@WebMethod(operationName = "InquiryByIdCustomer", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/InquiryByIdCustomer")
	@WebResult(name = "InquiryByIdCustomerResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "inquiryByIdCustomerResp")
	public InquiryByIdCustomerRespType inquiryByIdCustomer(
			@WebParam(name = "InquiryByIdCustomerRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", partName = "inquiryByIdCustomerReq") InquiryByIdCustomerReqType inquiryByIdCustomerReq)
			throws InquiryByIdCustomerFault;

}
