
package com.backoffice.client.customer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntCustomer service = new SrvIntCustomer();
* SrvIntCustomerInteface portType = service.getSrvIntCustomerPort();
* portType.register(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntCustomer", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", wsdlLocation = "http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntCustomer?wsdl")
@HandlerChain( file="SrvIntCustomer.xml" )
public class SrvIntCustomer extends Service {

	private final static URL SRVINTCUSTOMER_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.backoffice.client.customer.SrvIntCustomer.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.backoffice.client.customer.SrvIntCustomer.class.getResource(".");
			url = new URL(baseUrl, "http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntCustomer?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntCustomer?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTCUSTOMER_WSDL_LOCATION = url;
	}

	public SrvIntCustomer(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntCustomer() {
		super(SRVINTCUSTOMER_WSDL_LOCATION, new QName(
				"http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/", "SrvIntCustomer"));
	}

	/**
	 * 
	 * @return returns SrvIntCustomerInteface
	 */
	@WebEndpoint(name = "SrvIntCustomerPort")
	public SrvIntCustomerInteface getSrvIntCustomerPort() {
		return super.getPort(new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomer/",
				"SrvIntCustomerPort"), SrvIntCustomerInteface.class);
	}

}
