
package com.backoffice.client.validatecustomer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntCustomerOrq service = new SrvIntCustomerOrq();
* SrvIntCustomerOrqInteface portType = service.getSrvIntCustomerOrqPort();
* portType.validateCompliancesList(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntCustomerOrq", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomerOrq/", wsdlLocation = "http://172.16.16.53:7804/servicios/DireccionCanales/SrvIntCustomerOrq?wsdl")
@HandlerChain( file="SrvIntCustomerOrq.xml" )
public class SrvIntCustomerOrq extends Service {

	private final static URL SRVINTCUSTOMERORQ_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.backoffice.client.validatecustomer.SrvIntCustomerOrq.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.backoffice.client.validatecustomer.SrvIntCustomerOrq.class.getResource(".");
			url = new URL(baseUrl, "http://172.16.16.53:7804/servicios/DireccionCanales/SrvIntCustomerOrq?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.16.53:7804/servicios/DireccionCanales/SrvIntCustomerOrq?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTCUSTOMERORQ_WSDL_LOCATION = url;
	}

	public SrvIntCustomerOrq(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntCustomerOrq() {
		super(SRVINTCUSTOMERORQ_WSDL_LOCATION, new QName(
				"http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomerOrq/", "SrvIntCustomerOrq"));
	}

	/**
	 * 
	 * @return returns SrvIntCustomerOrqInteface
	 */
	@WebEndpoint(name = "SrvIntCustomerOrqPort")
	public SrvIntCustomerOrqInteface getSrvIntCustomerOrqPort() {
		return super.getPort(new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntCustomerOrq/",
				"SrvIntCustomerOrqPort"), SrvIntCustomerOrqInteface.class);
	}

}
