
package com.backoffice.client.otp;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "deleteFault", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/")
public class DeleteFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private DeleteFaultType faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public DeleteFault(String message, DeleteFaultType faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public DeleteFault(String message, DeleteFaultType faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: com.backoffice.client.otp.DeleteFaultType
	 */
	public DeleteFaultType getFaultInfo() {
		return faultInfo;
	}

}
