
package com.backoffice.client.otp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntOTPDiffuser service = new SrvIntOTPDiffuser();
* SrvIntOTPDiffuser portType = service.getSrvIntOTPDiffuserSOAP();
* portType.validate(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntOTPDiffuser", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", wsdlLocation = "file:/E:/WS/SrvIntOTPDiffuser_1.wsdl")
@HandlerChain(file="SrvIntOtpDiffuser.xml")
public class SrvIntOTPDiffuser_Service extends Service {

	private final static URL SRVINTOTPDIFFUSER_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.backoffice.client.otp.SrvIntOTPDiffuser_Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.backoffice.client.otp.SrvIntOTPDiffuser_Service.class.getResource(".");
			url = new URL(baseUrl, "file:/E:/WS/SrvIntOTPDiffuser_1.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/E:/WS/SrvIntOTPDiffuser_1.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTOTPDIFFUSER_WSDL_LOCATION = url;
	}

	public SrvIntOTPDiffuser_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntOTPDiffuser_Service() {
		super(SRVINTOTPDIFFUSER_WSDL_LOCATION, new QName(
				"http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", "SrvIntOTPDiffuser"));
	}

	/**
	 * 
	 * @return returns SrvIntOTPDiffuser
	 */
	@WebEndpoint(name = "SrvIntOTPDiffuserSOAP")
	public SrvIntOTPDiffuser getSrvIntOTPDiffuserSOAP() {
		return super.getPort(new QName("http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/",
				"SrvIntOTPDiffuserSOAP"), SrvIntOTPDiffuser.class);
	}

}
