
package com.backoffice.client.otp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SrvIntOTPDiffuser", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SrvIntOTPDiffuser {

	/**
	 * 
	 * @param validateReq
	 * @return returns com.backoffice.client.otp.ValidateRespType
	 * @throws ValidateFault
	 */
	@WebMethod(operationName = "Validate", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/Validate")
	@WebResult(name = "validateResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "validateResp")
	public ValidateRespType validate(
			@WebParam(name = "validateRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "validateReq") ValidateReqType validateReq)
			throws ValidateFault;

	/**
	 * 
	 * @param sendReq
	 * @return returns com.backoffice.client.otp.SendRespType
	 * @throws SendFault
	 */
	@WebMethod(operationName = "Send", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/Send")
	@WebResult(name = "sendResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "sendResp")
	public SendRespType send(
			@WebParam(name = "sendRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "sendReq") SendReqType sendReq)
			throws SendFault;

	/**
	 * 
	 * @param deleteReq
	 * @return returns com.backoffice.client.otp.DeleteRespType
	 * @throws DeleteFault
	 */
	@WebMethod(operationName = "Delete", action = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/Delete")
	@WebResult(name = "deleteResponse", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "deleteResp")
	public DeleteRespType delete(
			@WebParam(name = "deleteRequest", targetNamespace = "http://www.girosyfinanzas.com/servicios/DireccionCanales/SrvIntOTPDiffuser/", partName = "deleteReq") DeleteReqType deleteReq)
			throws DeleteFault;

}
