
package com.backoffice.client.products;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SrvIntProduct service = new SrvIntProduct();
* SrvIntProductInterface portType = service.getSrvIntProductPort();
* portType.getProductsByCustomer(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SrvIntProduct", targetNamespace = "http://www.girosyfinanzas/servicios/DireccionCanales/SrvIntProduct/", wsdlLocation = "http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntProduct/?wsdl")
@HandlerChain( file="SrvIntProducts.xml" )
public class SrvIntProduct extends Service {

	private final static URL SRVINTPRODUCT_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.backoffice.client.products.SrvIntProduct.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.backoffice.client.products.SrvIntProduct.class.getResource(".");
			url = new URL(baseUrl, "http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntProduct/?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.16.53:7802/servicios/DireccionCanales/SrvIntProduct/?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SRVINTPRODUCT_WSDL_LOCATION = url;
	}

	public SrvIntProduct(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SrvIntProduct() {
		super(SRVINTPRODUCT_WSDL_LOCATION,
				new QName("http://www.girosyfinanzas/servicios/DireccionCanales/SrvIntProduct/", "SrvIntProduct"));
	}

	/**
	 * 
	 * @return returns SrvIntProductInterface
	 */
	@WebEndpoint(name = "SrvIntProductPort")
	public SrvIntProductInterface getSrvIntProductPort() {
		return super.getPort(
				new QName("http://www.girosyfinanzas/servicios/DireccionCanales/SrvIntProduct/", "SrvIntProductPort"),
				SrvIntProductInterface.class);
	}

}
